---
title: "My title"
subtitle: "My subtitle if needed"
author: 
  - First author
  - Another author
thanks: "Code and data are available at: LINK."
date: today
date-format: long
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
```


# Introduction


# Data {#sec-data}


# Model

## Model set-up

The goal of our modeling strategy is to forecast if a person voted for Biden, based only on knowing their gender, race, and gun ownership status.

The model that we are interested in is:

\begin{align} 
y_i|\pi_i &\sim \mbox{Bern}(\pi_i) \\
\mbox{logit}(\pi_i) &= \alpha + \beta \times \mbox{gender}_i + \gamma \times \mbox{education}_i + \delta \times \mbox{gun}_i\\
\alpha &\sim \mbox{Normal}(0, 2.5) \\
\beta &\sim \mbox{Normal}(0, 2.5) \\
\gamma &\sim \mbox{Normal}(0, 2.5) \\
\delta &\sim \mbox{Normal}(0, 2.5)
\end{align}

Where:

* $y_i$ is the binary outcome variable, representing who respondent $i$ voted for and equal to 1 if Biden and 0 if Trump, 
* $\pi_i$ is the probability that respondent $i$ voted for Biden, 
* ${gender}_i$ is a predictor variable, representing the gender of respondent $i$, 
* ${race}_i$ is a predictor variable, representing the race of respondent $i$, and 
* ${gun}_i$ is a predictor variable, representing the gun ownership status of respondent $i$.

We used a logistic regression model in a Bayesian framework using the package `rstanarm` [@rstanarm], which we will briefly describe here. Logistic regression is a type of generalized linear model. It is a tool for data exploration and used when we are interested in the relationship between a binary outcome variable and some predictor variables. 

The foundation of logistic regression is the Bernoulli distribution and logit function. The Bernoulli distribution is a discrete probability distribution having two possible outcomes, “1” and “0”, in which “1” occurs with probability $p$ and “0” occurs with probability $1-p$. Logistic regression is still a linear model, because the predictor variables enter in a linear fashion [@rohan]. Hence, the logit function links the Bernoulli distribution to the machinery we use in linear models [@rohan].

In our model, we also have the parameters $\alpha$, $\beta$, $\gamma$, and $\delta$ in addition to the variables. The parameter $\alpha$ is the intercept and the parameters, $\beta$, $\gamma$, and $\delta$, are the slope coefficients. We specify prior probability distributions for each of the parameters in our model, but these are just the default priors that `rstanarm` [@rstanarm] uses (Normal distribution with mean and standard deviation of 0 and 2.5).

## Model justification


# Results


# Discussion

## First discussion point {#sec-first-point}

## Second discussion point

## Third discussion point

## Weaknesses and next steps


\newpage


\appendix

# Appendix {-}

# Additional data details

# Model details {#sec-model-details}


\newpage


# References
